players <- read.csv("players.csv",stringsAsFactors = FALSE)
divisions <- read.csv("divisions.csv",stringsAsFactors = FALSE)
batting <- read.csv("batting.csv",stringsAsFactors = FALSE)
pitching <- read.csv("pitching.csv",stringsAsFactors = FALSE)
games <- read.csv("games.csv",stringsAsFactors = FALSE)
teams <- read.csv("teams.csv", stringsAsFactors = FALSE)
prev_rankings <- read.csv("prev_rankings.csv", stringsAsFactors = FALSE)
saveRDS(batting,"tblBattingStatsFlat.rds")
saveRDS(pitching,"tblPitchingStatsFlat.rds")
saveRDS(games,"tblGames.rds")
saveRDS(players,"tblPlayers.rds")
saveRDS(divisions,"tblDivisions.rds")
saveRDS(teams,"tblTeams.rds")
saveRDS(prev_rankings,"previous_power_rankings.rds")